library(ggplot2)
library(pracma)
library(lamW)
library(ggpubr)
library(reshape2)

gammaijTimeHAT<-function(i,j,Tlag,Y,mean){
  if(missing(mean)){
    mean=F
  }
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  gam<-colMeans(0.5*(yi[(Tlag/(2*deltat)+1):Nt,1:Nx]-yi[1:(Nt-Tlag/(2*deltat)),1:Nx])*(yj[(Tlag/(2*deltat)+1):Nt,1:Nx]-yj[1:(Nt-Tlag/(2*deltat)),1:Nx]))
  if(mean){
    return(mean(gam))
  }
  else{return(gam)}
}
gammaijSpaceHAT<-function(i,j,Llag,Y,mean){
  if(missing(mean)){
    mean=F
  }
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  c<-Y[[5]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  gam<-rowMeans(0.5*(yi[1:Nt,(1+Llag/(2*deltat*c)):Nx]-yi[1:Nt,1:(Nx-Llag/(2*deltat*c))])*(yj[1:Nt,(1+Llag/(2*deltat*c)):Nx]-yj[1:Nt,1:(Nx-Llag/(2*deltat*c))]))
  if(mean){
    return(mean(gam))
  }
  else{return(gam)}
}
Cijhat0<-function(i,j,Y){#i,j=1,2
  yi<-Y[[i]]
  yj<-Y[[j]]
  return(mean(yi*yj))
}
CijhatTime<-function(i,j,Tlag,Y){#i,j=1,2
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  c<-Y[[5]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  return(colMeans(yi[1:(Nt-Tlag/(2*deltat)),1:(Nx)]*yj[(Tlag/(2*deltat)+1):Nt,(1):Nx]))
}
CijhatSpace<-function(i,j,Llag,Y){#i,j=1,2
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  c<-Y[[5]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  return(rowMeans(yi[1:(Nt),1:(Nx-Llag/(2*deltat*c))]*yj[(1):Nt,(1+Llag/(2*deltat*c)):Nx]))
}

C11Time<-function(Tlag,parameters,c){
  k11<-parameters$k11
  mu11<-parameters$mu11
  lambda11<-parameters$lambda11
  return(c*k11^2/(2*mu11*(mu11+c*lambda11))*(exp(-mu11*Tlag)))
}
C12Time<-function(Tlag,parameters,c){
  k11<-parameters$k11
  k21<-parameters$k21
  mu11<-parameters$mu11
  mu21<-parameters$mu21
  lambda11<-parameters$lambda11
  lambda21<-parameters$lambda21
  return((2*c*k11*k21)/((mu11+mu21)*(mu11+mu21+c*(lambda11+lambda21)))*(exp(-mu21*Tlag)))
}
C21Time<-function(Tlag,parameters,c){
  k11<-parameters$k11
  k21<-parameters$k21
  mu11<-parameters$mu11
  mu21<-parameters$mu21
  lambda11<-parameters$lambda11
  lambda21<-parameters$lambda21
  return((2*c*k11*k21)/((mu11+mu21)*(mu11+mu21+c*(lambda11+lambda21)))*(exp(-mu11*Tlag)))
}
C22Time<-function(Tlag,parameters,c){
  k21<-parameters$k21
  k22<-parameters$k22
  mu21<-parameters$mu21
  mu22<-parameters$mu22
  lambda21<-parameters$lambda21
  lambda22<-parameters$lambda22
  return(c*k21^2/(2*mu21*(mu21+c*lambda21))*(exp(-mu21*Tlag))+(c*k22^2/(2*mu22*(mu22+c*lambda22)))*(exp(-mu22*Tlag)))
}
C11Space<-function(Llag,parameters,c){
  k11<-parameters$k11
  mu11<-parameters$mu11
  lambda11<-parameters$lambda11
  return(c*k11^2/(2*mu11*(mu11+c*lambda11))*(exp(-(mu11/c+lambda11)*Llag)*(1+c*lambda11/mu11*(1-exp(-mu11/c*Llag)))))
}
C12Space<-function(Llag,parameters,c){
  k11<-parameters$k11
  k21<-parameters$k21
  mu11<-parameters$mu11
  mu21<-parameters$mu21
  lambda11<-parameters$lambda11
  lambda21<-parameters$lambda21
  return(c*k11*k21*exp(-(mu11+mu21)*(Llag/c))/(mu11+mu21)*(
    (exp(-lambda11*Llag)+exp(-lambda21*Llag))/(mu11+mu21+c*lambda11+c*lambda21)+
      exp(-lambda11*Llag)*(exp((mu11+mu21+c*lambda11-c*lambda21)*Llag/(2*c))-1)/(mu11+mu21+c*lambda11-c*lambda21)+
      exp(-lambda21*Llag)*(exp((mu11+mu21-c*lambda11+c*lambda21)*Llag/(2*c))-1)/(mu11+mu21-c*lambda11+c*lambda21)
  )
  )
}
C22Space<-function(Llag,parameters,c){
  k21<-parameters$k21
  k22<-parameters$k22
  mu21<-parameters$mu21
  mu22<-parameters$mu22
  lambda21<-parameters$lambda21
  lambda22<-parameters$lambda22
  return(c*k21^2/(2*mu21*(mu21+c*lambda21))*(exp(-(mu21/c+lambda21)*Llag)*(1+c*lambda21/mu21*(1-exp(-mu21/c*Llag))))+
           c*k22^2/(2*mu22*(mu22+c*lambda22))*(exp(-(mu22/c+lambda22)*Llag)*(1+c*lambda22/mu22*(1-exp(-mu22/c*Llag)))))
}

normalisedgammaijTimeHAT<-function(i,j,Tlag,Y,mean){
  if(missing(mean)){
    mean=F
  }
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  gam<-colMeans(0.5*(yi[(Tlag/(2*deltat)+1):Nt,1:Nx]-yi[1:(Nt-Tlag/(2*deltat)),1:Nx])*(yj[(Tlag/(2*deltat)+1):Nt,1:Nx]-yj[1:(Nt-Tlag/(2*deltat)),1:Nx]))
  cov0<-mean((yi[1:Nt,1:Nx])*(yj[1:Nt,1:Nx]))
  if(mean){
    return(mean(gam/cov0))
  }
  else{return(gam/cov0)}
}
normalisedgammaijSpaceHAT<-function(i,j,Llag,Y,mean){
  if(missing(mean)){
    mean=F
  }
  yi<-Y[[i]]
  yj<-Y[[j]]
  deltat<-Y[[6]]
  c<-Y[[5]]
  Nt<-dim(yi)[1]
  Nx<-dim(yi)[2]
  gam<-rowMeans(0.5*(yi[1:Nt,(1+Llag/(2*deltat*c)):Nx]-yi[1:Nt,1:(Nx-Llag/(2*deltat*c))])*(yj[1:Nt,(1+Llag/(2*deltat*c)):Nx]-yj[1:Nt,1:(Nx-Llag/(2*deltat*c))]))
  cov0<-mean((yi[1:Nt,1:Nx])*(yj[1:Nt,1:Nx]))
  if(mean){
    return(mean(gam/cov0))
  }
  else{return(gam/cov0)}
}

normalisedtheoreticalgamma11Time<-function(Tlag,parameters,c){1-C11Time(Tlag,parameters,c)/C11Time(0,parameters,c)}
normalisedtheoreticalgamma12Time<-function(Tlag,parameters,c){1-0.5*(C12Time(Tlag,parameters,c)+C21Time(Tlag,parameters,c))/C12Time(0,parameters,c)}
normalisedtheoreticalgamma22Time<-function(Tlag,parameters,c){1-C22Time(Tlag,parameters,c)/C22Time(0,parameters,c)}
normalisedtheoreticalgamma11Space<-function(Llag,parameters,c){1-C11Space(Llag,parameters,c)/C11Space(0,parameters,c)}
normalisedtheoreticalgamma12Space<-function(Llag,parameters,c){1-C12Space(Llag,parameters,c)/C12Space(0,parameters,c)}
normalisedtheoreticalgamma22Space<-function(Llag,parameters,c){1-C22Space(Llag,parameters,c)/C22Space(0,parameters,c)}

aslist<-function(vecparameters){return(list(k11=vecparameters[1],k21=vecparameters[2],k22=vecparameters[3],mu11=vecparameters[4],mu21=vecparameters[5],mu22=vecparameters[6],lambda11=vecparameters[7],lambda21=vecparameters[8],lambda22=vecparameters[9]))}

gammahatsijTime<-function(i,j,Y,timelags){
  Nx<-dim(Y[[1]])[2]
  NumberofLags<-length(timelags)
  output<-matrix(0,NumberofLags,Nx)
  for(k in 1:NumberofLags){
    Tlag<-timelags[k]
    output[k,]<-normalisedgammaijTimeHAT(i,j,Tlag,Y)
  }
  return(output)
}
gammahatsijSpace<-function(i,j,Y,spacelags){
  Nt<-dim(Y[[1]])[1]
  NumberofLags<-length(spacelags)
  output<-matrix(0,NumberofLags,Nt)
  for(k in 1:NumberofLags){
    Llag<-spacelags[k]
    output[k,]<-normalisedgammaijSpaceHAT(i,j,Llag,Y)
  }
  return(output)
}
ChatsijTime<-function(i,j,Y,timelags){
  timelags0<-c(0,timelags)
  Nx<-dim(Y[[1]])[2]
  output<-matrix(0,length(timelags0),Nx)
  for(k in 1:length(timelags0)){
    Tlag<-timelags0[k]
    output[k,]<-CijhatTime(i,j,Tlag,Y)
  }
  return(output)
}

E11Time<-function(mu11,estimatedparas,Y,timelags,gammahats){
  NumberofLags<-length(timelags)
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  E11timemat<-matrix(0,NumberofLags,Nx)
  parameters<-estimatedparas
  parameters$mu11<-mu11
  for(i in 1:NumberofLags){
    Tlag<-timelags[i]
    E11timemat[i,]<-gammahats[i,]-normalisedtheoreticalgamma11Time(Tlag,parameters,c)
  }
  return(E11timemat)
}
loss11time<-function(mu11,estimatedparas,Y,timelags,S,gammahats){
  e11<-E11Time(mu11,estimatedparas,Y,timelags,gammahats)
  lossfunction<-t(rowSums(e11))%*%S%*%(rowSums(e11))
  return(lossfunction)
} #Should be scaled maybe if combining with others but for now we are not

E12Time<-function(mu21,estimatedparas,Y,timelags,gammahats){
  NumberofLags<-length(timelags)
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  E12timemat<-matrix(0,NumberofLags,Nx)
  parameters<-estimatedparas
  parameters$mu21<-mu21
  for(i in 1:NumberofLags){
    Tlag<-timelags[i]
    E12timemat[i,]<-gammahats[i,]-normalisedtheoreticalgamma12Time(Tlag,parameters,c)
  }
  return(E12timemat)
}
loss12time<-function(mu21,estimatedparas,Y,timelags,S,gammahats){
  e12<-E12Time(mu21,estimatedparas,Y,timelags,gammahats)
  lossfunction<-t(rowSums(e12))%*%S%*%(rowSums(e12))
  return(lossfunction)
}

E11Space<-function(lambda11,estimatedparas,Y,spacelags,gammahats){
  NumberofLags<-length(spacelags)
  c<-Y[[5]]
  Nt<-dim(Y[[1]])[1]
  E11spaceemat<-matrix(0,NumberofLags,Nt)
  parameters<-estimatedparas
  parameters$lambda11<-lambda11
  for(i in 1:NumberofLags){
    Llag<-spacelags[i]
    E11spaceemat[i,]<-gammahats[i,]-normalisedtheoreticalgamma11Space(Llag,parameters,c)
  }
  return(E11spaceemat)
}
loss11space<-function(lambda11,estimatedparas,Y,spacelags,S,gammahats){
  e11<-E11Space(lambda11,estimatedparas,Y,spacelags,gammahats)
  lossfunction<-t(rowSums(e11))%*%S%*%(rowSums(e11))
  return(lossfunction)
}

E12Space<-function(lambda21,estimatedparas,Y,spacelags,gammahats){
  NumberofLags<-length(spacelags)
  c<-Y[[5]]
  Nt<-dim(Y[[1]])[1]
  E12spaceemat<-matrix(0,NumberofLags,Nt)
  parameters<-estimatedparas
  parameters$lambda21<-lambda21
  for(i in 1:NumberofLags){
    Llag<-spacelags[i]
    E12spaceemat[i,]<-gammahats[i,]-normalisedtheoreticalgamma12Space(Llag,parameters,c)
  }
  return(E12spaceemat)
}
loss12space<-function(lambda21,estimatedparas,Y,spacelags,S,gammahats){
  e12<-E12Space(lambda21,estimatedparas,Y,spacelags,gammahats)
  lossfunction<-t(rowSums(e12))%*%S%*%(rowSums(e12))
  return(lossfunction)
}

CovE11Time<-function(k11,estimatedparas,Y,timelags,Chats){
  timelags0<-c(0,timelags) #including the zero lag as we now have covaraince
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  CovE11timeemat<-matrix(0,length(timelags0),Nx)
  parameters<-estimatedparas
  parameters$k11<-k11
  for(i in 1:length(timelags0)){
    Tlag<-timelags0[i]
    CovE11timeemat[i,]<-Chats[i,]-C11Time(timelags0[i],parameters,c)
  }
  return(CovE11timeemat)
}
lossCov11time<-function(k11,estimatedparas,Y,timelags,S,Chats){
  e11<-CovE11Time(k11,estimatedparas,Y,timelags,Chats)
  lossfunction<-t(rowSums(e11))%*%S%*%rowSums(e11)
  return(lossfunction)
}

CovE12Time<-function(k21,estimatedparas,Y,timelags,Chats){
  timelags0<-c(0,timelags) #including the zero lag as we now have covaraince
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  CovE12timeemat<-matrix(0,length(timelags0),Nx)
  parameters<-estimatedparas
  parameters$k21<-k21
  for(i in 1:length(timelags0)){
    Tlag<-timelags0[i]
    CovE12timeemat[i,]<-Chats[i,]-C12Time(timelags0[i],parameters,c)
  }
  return(CovE12timeemat)
}
lossCov12time<-function(k21,estimatedparas,Y,timelags,S,Chats){
  e12<-CovE12Time(k21,estimatedparas,Y,timelags,Chats)
  lossfunction<-t(rowSums(e12))%*%S%*%rowSums(e12)
  return(lossfunction)
}

half22normalisedgamma22Time<-function(Tlag,parameters,c){
  parametersk22is0<-parameters
  parametersk22is0$k22<-0
  1-(C22Time(Tlag,parameters,c)-C22Time(Tlag,parametersk22is0,c))/(C22Time(0,parameters,c)-C22Time(0,parametersk22is0,c))
}
half22normalisedgamma22TimeHAT<-function(Tlag,parameters,c,Y){
  parametersk22is0<-parameters
  parametersk22is0$k22<-0
  1-(CijhatTime(2,2,Tlag,Y)-C22Time(Tlag,parametersk22is0,c))/(CijhatTime(2,2,0,Y)-C22Time(0,parametersk22is0,c))
}
halfgammahats22Time<-function(timelags,parameters,c,Y){
  Nx<-dim(Y[[1]])[2]
  NumberofLags<-length(timelags)
  output<-matrix(0,NumberofLags,Nx)
  for(k in 1:NumberofLags){
    Tlag<-timelags[k]
    output[k,]<-half22normalisedgamma22TimeHAT(Tlag,parameters,c,Y)
  }
  return(output)
}
E22timeHalf<-function(mu22,estimatedparas,Y,timelags,halfgammahats){
  NumberofLags<-length(timelags)
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  E22timemat<-matrix(0,NumberofLags,Nx)
  parameters<-estimatedparas
  parameters$mu22<-mu22
  for(i in 1:NumberofLags){
    Tlag<-timelags[i]
    E22timemat[i,]<-halfgammahats[i,]-half22normalisedgamma22Time(Tlag,parameters,c)
  }
  return(E22timemat)
}
loss22timeHalf<-function(mu22,estimatedparas,Y,timelags,S,halfgammahats){
  e22<-E22timeHalf(mu22,estimatedparas,Y,timelags,halfgammahats)
  lossfunction<-t(rowSums(e22))%*%S%*%(rowSums(e22))
  return(lossfunction)
}

half22normalisedgamma22Space<-function(Llag,parameters,c){
  parametersk22is0<-parameters
  parametersk22is0$k22<-0
  1-(C22Space(Llag,parameters,c)-C22Space(Llag,parametersk22is0,c))/(C22Space(0,parameters,c)-C22Space(0,parametersk22is0,c))
}
half22normalisedgamma22SpaceHAT<-function(Llag,parameters,c,Y){
  parametersk22is0<-parameters
  parametersk22is0$k22<-0
  1-(CijhatSpace(2,2,Llag,Y)-C22Space(Llag,parametersk22is0,c))/(CijhatSpace(2,2,0,Y)-C22Space(0,parametersk22is0,c))
}
halfgammahats22Space<-function(spacelags,parameters,c,Y){
  Nt<-dim(Y[[1]])[1]
  NumberofLags<-length(spacelags)
  output<-matrix(0,NumberofLags,Nt)
  for(k in 1:NumberofLags){
    Llag<-spacelags[k]
    output[k,]<-half22normalisedgamma22SpaceHAT(Llag,parameters,c,Y)
  }
  return(output)
}
E22spaceHalf<-function(lambda22,estimatedparas,Y,spacelags,halfgammahats){
  NumberofLags<-length(spacelags)
  c<-Y[[5]]
  Nt<-dim(Y[[1]])[1]
  E22spacemat<-matrix(0,NumberofLags,Nt)
  parameters<-estimatedparas
  parameters$lambda22<-lambda22
  for(i in 1:NumberofLags){
    Llag<-spacelags[i]
    E22spacemat[i,]<-halfgammahats[i,]-half22normalisedgamma22Space(Llag,parameters,c)
  }
  return(E22spacemat)
}
loss22spaceHalf<-function(lambda22,estimatedparas,Y,spacelags,S,halfgammahats){
  e22<-E22spaceHalf(lambda22,estimatedparas,Y,spacelags,halfgammahats)
  lossfunction<-t(rowSums(e22))%*%S%*%(rowSums(e22))
  return(lossfunction)
}

CovE22Time<-function(k22,estimatedparas,Y,timelags,Chats){
  timelags0<-c(0,timelags) #including the zero lag as we now have covaraince
  c<-Y[[5]]
  Nx<-dim(Y[[1]])[2]
  CovE22timeemat<-matrix(0,length(timelags0),Nx)
  parameters<-estimatedparas
  parameters$k22<-k22
  for(i in 1:length(timelags0)){
    Tlag<-timelags0[i]
    CovE22timeemat[i,]<-Chats[i,]-C22Time(timelags0[i],parameters,c)
  }
  return(CovE22timeemat)
}
lossCov22time<-function(k22,estimatedparas,Y,timelags,S,Chats){
  e22<-CovE22Time(k22,estimatedparas,Y,timelags,Chats)
  lossfunction<-t(rowSums(e22))%*%S%*%rowSums(e22)
  return(lossfunction)
}


getmu11<-function(Y,initialmu11,estimatedparas,timelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags)
  dif<-1
  gammahats<-gammahatsijTime(1,1,Y,timelags)
  previousguess<-initialmu11
  while(dif>tol){
    mu11hat<-optim(initialmu11,function(mu11){loss11time(mu11,estimatedparas,Y,timelags,S,gammahats)},method="BFGS")$par
    if(!Weights){break}
    e11<-E11Time(mu11hat,estimatedparas,Y,timelags,gammahats)
    omega<-e11%*%t(e11)
    S<-solve(omega)
    dif<-abs(previousguess-mu11hat)/mu11hat
    previousguess<-mu11hat
  }
  return(mu11hat)
}
getmu21<-function(Y,initialmu21,estimatedparas,timelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags)
  dif<-1
  gammahats<-gammahatsijTime(1,2,Y,timelags)
  previousguess<-initialmu21
  while(dif>tol){
    mu21hat<-optim(initialmu21,function(mu21){loss12time(mu21,estimatedparas,Y,timelags,S,gammahats)},method="BFGS")$par
    #print(mu21hat)
    if(!Weights){break}
    e12<-E12Time(mu21hat,estimatedparas,Y,timelags,gammahats)
    omega<-e12%*%t(e12)
    S<-solve(omega)
    dif<-abs(previousguess-mu21hat)/mu21hat
    previousguess<-mu21hat
  }
  return(mu21hat)
}
getlambda11<-function(Y,initiallambda11,estimatedparas,spacelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(spacelags)
  S<-diag(NumberofLags)
  dif<-1
  gammahats<-gammahatsijSpace(1,1,Y,spacelags)
  previousguess<-initiallambda11
  while(dif>tol){
    lambda11hat<-optim(initiallambda11,function(lambda11){loss11space(lambda11,estimatedparas,Y,spacelags,S,gammahats)},method="BFGS")$par
    if(!Weights){break}
    e11<-E11Space(lambda11hat,estimatedparas,Y,spacelags,gammahats)
    omega<-e11%*%t(e11)
    S<-solve(omega)
    dif<-abs(previousguess-lambda11hat)/lambda11hat
    previousguess<-lambda11hat
  }
  return(lambda11hat)
}
getlambda21<-function(Y,initiallambda21,estimatedparas,spacelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(spacelags)
  S<-diag(NumberofLags)
  dif<-1
  gammahats<-gammahatsijSpace(1,2,Y,spacelags)
  previousguess<-initiallambda21
  while(dif>tol){
    lambda21hat<-optim(initiallambda21,function(lambda21){loss12space(lambda21,estimatedparas,Y,spacelags,S,gammahats)},method="BFGS")$par
    if(!Weights){break}
    e12<-E12Space(lambda21hat,estimatedparas,Y,spacelags,gammahats)
    omega<-e12%*%t(e12)
    S<-solve(omega)
    dif<-abs(previousguess-lambda21hat)/lambda21hat
    previousguess<-lambda21hat
  }
  return(lambda21hat)
}
getk11<-function(Y,initialk11,estimatedparas,timelags,tol,Weights){
  Chats<-ChatsijTime(1,1,Y,timelags)
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags+1)
  dif<-1
  previousguess<-initialk11
  while(dif>tol){
    k11hat<-optim(initialk11,function(k11){lossCov11time(k11,estimatedparas,Y,timelags,S,Chats)},method="BFGS")$par
    if(!Weights){break}
    e11<-CovE11Time(k11hat,estimatedparas,Y,timelags,Chats)
    omega<-e11%*%t(e11)
    S<-solve(omega)
    dif<-abs(previousguess-k11hat)/k11hat
    previousguess<-k11hat
  }
  return(k11hat)
}
getk21<-function(Y,initialk21,estimatedparas,timelags,tol,Weights){
  Chats<-ChatsijTime(1,2,Y,timelags)
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags+1)
  dif<-1
  previousguess<-initialk21
  while(dif>tol){
    k21hat<-optim(initialk21,function(k21){lossCov12time(k21,estimatedparas,Y,timelags,S,Chats)},method="BFGS")$par
    if(!Weights){break}
    e12<-CovE12Time(k21hat,estimatedparas,Y,timelags,Chats)
    omega<-e12%*%t(e12)
    S<-solve(omega)
    dif<-abs(previousguess-k21hat)/k21hat
    previousguess<-k21hat
  }
  return(k21hat)
}
getmu22<-function(Y,initialmu22,estimatedparas,timelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  c<-Y[[5]]
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags)
  dif<-1
  halfgammahats<-halfgammahats22Time(timelags,estimatedparas,c,Y)
  previousguess<-initialmu22
  while(dif>tol){
    mu22hat<-optim(initialmu22,function(mu22){loss22timeHalf(mu22,estimatedparas,Y,timelags,S,halfgammahats)},method="BFGS")$par
    e22<-E22timeHalf(mu22hat,estimatedparas,Y,timelags,halfgammahats)
    omega<-e22%*%t(e22)
    S<-solve(omega)
    dif<-abs(previousguess-mu22hat)/mu22hat
    previousguess<-mu22hat
  }
  return(mu22hat)
}
getlambda22<-function(Y,initiallambda22,estimatedparas,spacelags,tol,Weights){
  if(missing(Weights)){Weights<-T}
  c<-Y[[5]]
  NumberofLags<-length(spacelags)
  S<-diag(NumberofLags)
  dif<-1
  halfgammahats<-halfgammahats22Space(spacelags,estimatedparas,c,Y)
  previousguess<-initiallambda22
  while(dif>tol){
    lambda22hat<-optim(initiallambda22,function(lambda22){loss22spaceHalf(lambda22,estimatedparas,Y,spacelags,S,halfgammahats)},method="L-BFGS-B",lower=0)$par
    e22<-E22spaceHalf(lambda22hat,estimatedparas,Y,spacelags,halfgammahats)
    omega<-e22%*%t(e22)
    S<-solve(omega)
    dif<-abs(previousguess-lambda22hat)/lambda22hat
    previousguess<-lambda22hat
  }
  return(lambda22hat)
  }
getk22<-function(Y,initialk22,estimatedparas,timelags,tol,Weights){
  Chats<-ChatsijTime(2,2,Y,timelags)
  if(missing(Weights)){Weights<-T}
  NumberofLags<-length(timelags)
  S<-diag(NumberofLags+1)
  dif<-1
  previousguess<-initialk22
  while(dif>tol){
    k22hat<-optim(initialk22,function(k22){lossCov22time(k22,estimatedparas,Y,timelags,S,Chats)},method="BFGS")$par
    if(!Weights){break}
    e22<-CovE22Time(k22hat,estimatedparas,Y,timelags,Chats)
    omega<-e22%*%t(e22)
    S<-solve(omega)
    dif<-abs(previousguess-k22hat)/k22hat
    previousguess<-k22hat
  }
  return(k22hat)
}


getparametersOAAT<-function(Y,K,initialparas,tol){
  if(missing(initialparas)){initialparas<-aslist(c(1,1,1,1,1,1,1,1,1))}
  if(missing(tol)){tol<-0.001}
  c<-Y[[5]]
  deltat<-Y[[6]]
  #NumberofLags<-K
  timelags<-((1:K))*2*deltat
  spacelags<-((1:K))*2*deltat*c
  estimatedparas<-initialparas
  estimatedparas$mu11<-getmu11(Y,initialparas$mu11,estimatedparas,timelags,tol,F)
  estimatedparas$mu21<-getmu21(Y,initialparas$mu21,estimatedparas,timelags,tol,T)
  estimatedparas$lambda11<-getlambda11(Y,initialparas$lambda11,estimatedparas,spacelags,tol,T)
  estimatedparas$lambda21<-getlambda21(Y,initialparas$lambda21,estimatedparas,spacelags,tol,T)
  estimatedparas$k11<-getk11(Y,initialparas$k11,estimatedparas,timelags,tol,T)
  estimatedparas$k21<-getk21(Y,initialparas$k21,estimatedparas,timelags,tol,T)
  estimatedparas$mu22<-getmu22(Y,initialparas$mu22,estimatedparas,timelags,tol,T)
  estimatedparas$lambda22<-getlambda22(Y,initialparas$lambda22,estimatedparas,spacelags,tol,T)
  estimatedparas$k22<-getk22(Y,initialparas$k22,estimatedparas,timelags,tol,T)
  return(estimatedparas)
}



Y<-readRDS("Output Fields/newparasfine3.rds")
Y<-readRDS("Output Fields/highrespointone.rds1.rds")
Y<-readRDS("Output Fields/highrespointone.rds2.rds")
Y<-readRDS("Output Fields/highrespointone.rds3.rds")
Y<-readRDS("Output Fields/highrespointone.rds4.rds")

Y<-readRDS(("Output Fields/bulk01v17.rds"))

as.numeric(getparametersOAAT(Y,10))
round(as.numeric(getparametersOAAT(Y,10))-as.numeric(Y[[7]]),2)
as.numeric(getparametersOAAT(Y,10))

estimatedparas<-aslist(c(1,1,1,1,1,1,1,1,1))
c<-Y[[5]]
deltat<-Y[[6]]
NumberofLags<-10


K<-10
timelags<-((1:K))*2*deltat
spacelags<-((1:K))*2*deltat*c

#PLOt variograms estimated and true
varplotdata<-matrix(0,K,3)
for(i in 1:K){
  Tlag<-timelags[i]
  #varplotdata[i,1]<-normalisedtheoreticalgamma12Time(Tlag,estimatedparas,c)
  varplotdata[i,2]<-normalisedtheoreticalgamma12Time(Tlag,Y[[7]],c)
  varplotdata[i,3]<-mean(normalisedgammaijTimeHAT(1,2,Tlag,Y))
}
dat<-data.frame(timelags,varplotdata)
colnames(dat)<-c("Lags","estimated","true","calculated")
ggplot(dat)+#geom_line(aes(x=Lags,y=estimated))+
  geom_line(aes(x=Lags,y=true),col="blue")+
  geom_point(aes(x=Lags,y=calculated))
